version: "3"

services:

  client_api:
    build: ./client_api/.
    ports:
      - 8080:8080
    depends_on:
      - port_domain_service
    environment:
      PORT_DOMAIN_HOST: port_domain_service
      PORT_DOMAIN_PORT: 50051

  port_domain_service:
    build: ./port_domain_service/.
    depends_on:
      - mongo
    ports:
      - 50051:50051
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: supersecret
      MONGO_INITDB_DATABASE: port_db
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - ./mongo_init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo_test:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: supersecret
      MONGO_INITDB_DATABASE: port_db
    ports:
      - 27018:27017
    volumes:
      - mongo_test_data:/data/db
      - ./mongo_init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo_data:
    driver: local
  mongo_test_data:
    driver: local
