// Code generated by protoc-gen-go. DO NOT EDIT.
// source: port.proto

package portpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Port struct {
	Abbreviation         string    `protobuf:"bytes,1,opt,name=abbreviation,proto3" json:"abbreviation,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Coordinates          []float64 `protobuf:"fixed64,3,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	City                 string    `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Province             string    `protobuf:"bytes,5,opt,name=province,proto3" json:"province,omitempty"`
	Country              string    `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Alias                []string  `protobuf:"bytes,7,rep,name=alias,proto3" json:"alias,omitempty"`
	Regions              []string  `protobuf:"bytes,8,rep,name=regions,proto3" json:"regions,omitempty"`
	Timezone             string    `protobuf:"bytes,9,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Unlocs               []string  `protobuf:"bytes,10,rep,name=unlocs,proto3" json:"unlocs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_729c3d36e9010a8e, []int{0}
}

func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (m *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(m, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetAbbreviation() string {
	if m != nil {
		return m.Abbreviation
	}
	return ""
}

func (m *Port) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Port) GetCoordinates() []float64 {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *Port) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Port) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *Port) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Port) GetAlias() []string {
	if m != nil {
		return m.Alias
	}
	return nil
}

func (m *Port) GetRegions() []string {
	if m != nil {
		return m.Regions
	}
	return nil
}

func (m *Port) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *Port) GetUnlocs() []string {
	if m != nil {
		return m.Unlocs
	}
	return nil
}

type ImportResponse struct {
	NumberInserted       int32    `protobuf:"varint,1,opt,name=number_inserted,json=numberInserted,proto3" json:"number_inserted,omitempty"`
	NumberUpdated        int32    `protobuf:"varint,2,opt,name=number_updated,json=numberUpdated,proto3" json:"number_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportResponse) Reset()         { *m = ImportResponse{} }
func (m *ImportResponse) String() string { return proto.CompactTextString(m) }
func (*ImportResponse) ProtoMessage()    {}
func (*ImportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_729c3d36e9010a8e, []int{1}
}

func (m *ImportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportResponse.Unmarshal(m, b)
}
func (m *ImportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportResponse.Marshal(b, m, deterministic)
}
func (m *ImportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportResponse.Merge(m, src)
}
func (m *ImportResponse) XXX_Size() int {
	return xxx_messageInfo_ImportResponse.Size(m)
}
func (m *ImportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImportResponse proto.InternalMessageInfo

func (m *ImportResponse) GetNumberInserted() int32 {
	if m != nil {
		return m.NumberInserted
	}
	return 0
}

func (m *ImportResponse) GetNumberUpdated() int32 {
	if m != nil {
		return m.NumberUpdated
	}
	return 0
}

type GetPortRequest struct {
	Abbreviation         string   `protobuf:"bytes,1,opt,name=abbreviation,proto3" json:"abbreviation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPortRequest) Reset()         { *m = GetPortRequest{} }
func (m *GetPortRequest) String() string { return proto.CompactTextString(m) }
func (*GetPortRequest) ProtoMessage()    {}
func (*GetPortRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_729c3d36e9010a8e, []int{2}
}

func (m *GetPortRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPortRequest.Unmarshal(m, b)
}
func (m *GetPortRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPortRequest.Marshal(b, m, deterministic)
}
func (m *GetPortRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPortRequest.Merge(m, src)
}
func (m *GetPortRequest) XXX_Size() int {
	return xxx_messageInfo_GetPortRequest.Size(m)
}
func (m *GetPortRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPortRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPortRequest proto.InternalMessageInfo

func (m *GetPortRequest) GetAbbreviation() string {
	if m != nil {
		return m.Abbreviation
	}
	return ""
}

func init() {
	proto.RegisterType((*Port)(nil), "portpb.Port")
	proto.RegisterType((*ImportResponse)(nil), "portpb.ImportResponse")
	proto.RegisterType((*GetPortRequest)(nil), "portpb.GetPortRequest")
}

func init() { proto.RegisterFile("port.proto", fileDescriptor_729c3d36e9010a8e) }

var fileDescriptor_729c3d36e9010a8e = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x6b, 0xea, 0x40,
	0x10, 0xc7, 0x8d, 0xd1, 0xa8, 0xa3, 0xcf, 0x07, 0xc3, 0x43, 0x16, 0x4f, 0x21, 0xf0, 0x68, 0x2e,
	0xf5, 0x60, 0xfb, 0x09, 0x7a, 0x11, 0x6f, 0x92, 0xd2, 0x4b, 0x2f, 0x36, 0x89, 0x43, 0x59, 0x30,
	0xbb, 0xe9, 0xee, 0x46, 0xb0, 0x1f, 0xa2, 0x9f, 0xb9, 0xec, 0x6e, 0x22, 0xcd, 0xad, 0xb7, 0xf9,
	0xff, 0x66, 0xfe, 0x3b, 0xcc, 0xec, 0x00, 0xd4, 0x52, 0x99, 0x4d, 0xad, 0xa4, 0x91, 0x18, 0xd9,
	0xb8, 0x2e, 0x92, 0xaf, 0x21, 0x8c, 0x0e, 0x52, 0x19, 0x4c, 0x60, 0x91, 0x17, 0x85, 0xa2, 0x0b,
	0xcf, 0x0d, 0x97, 0x82, 0x05, 0x71, 0x90, 0xce, 0xb2, 0x1e, 0x43, 0x84, 0x91, 0xc8, 0x2b, 0x62,
	0x43, 0x97, 0x73, 0x31, 0xc6, 0x30, 0x2f, 0xa5, 0x54, 0x27, 0x2e, 0x72, 0x43, 0x9a, 0x85, 0x71,
	0x98, 0x06, 0xd9, 0x4f, 0x64, 0x5d, 0x25, 0x37, 0x57, 0x36, 0xf2, 0x2e, 0x1b, 0xe3, 0x1a, 0xa6,
	0xb5, 0x92, 0x17, 0x2e, 0x4a, 0x62, 0x63, 0xc7, 0x6f, 0x1a, 0x19, 0x4c, 0x4a, 0xd9, 0x08, 0xa3,
	0xae, 0x2c, 0x72, 0xa9, 0x4e, 0xe2, 0x3f, 0x18, 0xe7, 0x67, 0x9e, 0x6b, 0x36, 0x89, 0xc3, 0x74,
	0x96, 0x79, 0x61, 0xeb, 0x15, 0xbd, 0x73, 0x29, 0x34, 0x9b, 0x3a, 0xde, 0x49, 0xdb, 0xc5, 0xf0,
	0x8a, 0x3e, 0xa5, 0x20, 0x36, 0xf3, 0x5d, 0x3a, 0x8d, 0x2b, 0x88, 0x1a, 0x71, 0x96, 0xa5, 0x66,
	0xe0, 0x4c, 0xad, 0x4a, 0xde, 0x60, 0xb9, 0xaf, 0xec, 0x72, 0x32, 0xd2, 0xb5, 0x14, 0x9a, 0xf0,
	0x0e, 0xfe, 0x8a, 0xa6, 0x2a, 0x48, 0x1d, 0xb9, 0xd0, 0xa4, 0x0c, 0x9d, 0xdc, 0x72, 0xc6, 0xd9,
	0xd2, 0xe3, 0x7d, 0x4b, 0xf1, 0x3f, 0xb4, 0xe4, 0xd8, 0xd4, 0xa7, 0xdc, 0xd6, 0x0d, 0x5d, 0xdd,
	0x1f, 0x4f, 0x5f, 0x3c, 0x4c, 0x1e, 0x61, 0xb9, 0x23, 0x73, 0x70, 0x2d, 0x3e, 0x1a, 0xd2, 0xbf,
	0xda, 0xfd, 0xb6, 0x86, 0xb9, 0xb5, 0x3c, 0x93, 0xba, 0xf0, 0x92, 0xf0, 0x1e, 0xc2, 0x1d, 0x19,
	0x5c, 0x6d, 0xfc, 0x3f, 0x6e, 0xfa, 0x2f, 0xae, 0x17, 0x1d, 0xb7, 0x30, 0x19, 0xe0, 0x16, 0x22,
	0x3f, 0x15, 0xf6, 0x32, 0xeb, 0x9b, 0xbf, 0x3f, 0x73, 0x32, 0x48, 0x83, 0xa7, 0xe9, 0x6b, 0x7b,
	0x24, 0x45, 0xe4, 0x6e, 0xe6, 0xe1, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x00, 0xbd, 0xff, 0x17, 0x41,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PortServiceClient is the client API for PortService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PortServiceClient interface {
	Get(ctx context.Context, in *GetPortRequest, opts ...grpc.CallOption) (*Port, error)
	Import(ctx context.Context, opts ...grpc.CallOption) (PortService_ImportClient, error)
}

type portServiceClient struct {
	cc *grpc.ClientConn
}

func NewPortServiceClient(cc *grpc.ClientConn) PortServiceClient {
	return &portServiceClient{cc}
}

func (c *portServiceClient) Get(ctx context.Context, in *GetPortRequest, opts ...grpc.CallOption) (*Port, error) {
	out := new(Port)
	err := c.cc.Invoke(ctx, "/portpb.PortService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portServiceClient) Import(ctx context.Context, opts ...grpc.CallOption) (PortService_ImportClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PortService_serviceDesc.Streams[0], "/portpb.PortService/Import", opts...)
	if err != nil {
		return nil, err
	}
	x := &portServiceImportClient{stream}
	return x, nil
}

type PortService_ImportClient interface {
	Send(*Port) error
	CloseAndRecv() (*ImportResponse, error)
	grpc.ClientStream
}

type portServiceImportClient struct {
	grpc.ClientStream
}

func (x *portServiceImportClient) Send(m *Port) error {
	return x.ClientStream.SendMsg(m)
}

func (x *portServiceImportClient) CloseAndRecv() (*ImportResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ImportResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PortServiceServer is the server API for PortService service.
type PortServiceServer interface {
	Get(context.Context, *GetPortRequest) (*Port, error)
	Import(PortService_ImportServer) error
}

// UnimplementedPortServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPortServiceServer struct {
}

func (*UnimplementedPortServiceServer) Get(ctx context.Context, req *GetPortRequest) (*Port, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedPortServiceServer) Import(srv PortService_ImportServer) error {
	return status.Errorf(codes.Unimplemented, "method Import not implemented")
}

func RegisterPortServiceServer(s *grpc.Server, srv PortServiceServer) {
	s.RegisterService(&_PortService_serviceDesc, srv)
}

func _PortService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portpb.PortService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).Get(ctx, req.(*GetPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortService_Import_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PortServiceServer).Import(&portServiceImportServer{stream})
}

type PortService_ImportServer interface {
	SendAndClose(*ImportResponse) error
	Recv() (*Port, error)
	grpc.ServerStream
}

type portServiceImportServer struct {
	grpc.ServerStream
}

func (x *portServiceImportServer) SendAndClose(m *ImportResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *portServiceImportServer) Recv() (*Port, error) {
	m := new(Port)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PortService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "portpb.PortService",
	HandlerType: (*PortServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _PortService_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Import",
			Handler:       _PortService_Import_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "port.proto",
}
